cargo-features = ["codegen-backend"]

[profile.dev]
opt-level = 1
debug = true
overflow-checks = true
lto = false
incremental = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
incremental = true

[workspace]
members = [
    "./crates/core",
    "./crates/shared",
]
exclude = [
    "./crates/plugins/drums",
    "./crates/plugins/sample_egui_plugin",
    "./crates/plugins/midi_korg_nano_kontrol",
    "./crates/plugins/visualizer",
    "./crates/plugins/serial",
    "./crates/plugin_framework",
]
resolver = "2"

