[package]
name = "blaulicht-audio-engine"
version = "0.3.0"
authors = ["MikMuellerDev"]
edition = "2021"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.76"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]


[features]
default = ["stream_in", "file", "noise"]
stream_in = ["dep:cpal", "dep:audioviz"]
file = [ "dep:symphonia", "stream_in" ]
noise = ["dep:rand"]

[dependencies]
log = "0.4"

# stream_in, file
# audioviz = { path = "../../../audioviz/", features = ["serde"], optional = true }
audioviz = { version = "0.6.0", features = ["serde"], optional = true }
cpal = { version = "0.15.3", optional = true }

# file
symphonia = { version = "0.5.5", features = ["mp3"], optional = true }

# noise
rand = { version = "0.9.2", optional = true }

# TODO: remove all of this.
crossbeam-channel = "0.5.15"
itertools = "0.14.0"
blaulicht-shared = { path = "../shared" }
egui = "0.32"
anyhow = "1.0.100"
serde = { version = "1", features = ["derive"] }
map-range = "0.1.2"
image = "0.25.6"
kdam = "0.6.3"
clap = { version = "4.5.21", features = ["derive"] }
savgol-rs = "0.1.0"


[target.'cfg(target_os = "macos")'.dependencies]
mach = "0.3"
libc = "0.2"

# [profile.release]
# opt-level = 3
