use crate::app::{components, BlaulichtApp};
use crate::state::ScreenId;
use blaulicht_shared::{
    ControlEvent, ControlEventMessage, EventOriginator, MainUiEvent, PluginUiEvent,
};
use egui::Context;
use strum::IntoEnumIterator;

pub(crate) fn notify_plugin_ui_open(
    data: &crate::state::AppStateWrapper,
    plugin_id: u8,
    open: bool,
) {
    data.event_bus_connection.send(ControlEventMessage::new(
        EventOriginator::Web,
        ControlEvent::MainUi(MainUiEvent::SetPluginUIOpen { plugin_id, open }),
    ));
}

/// Window/pane title for a plugin UI: the numeric id plus the plugin's file
/// stem, so several open plugin windows can be told apart.
pub(crate) fn plugin_ui_title(data: &crate::state::AppStateWrapper, plugin_id: u8) -> String {
    let name = data
        .state
        .plugins
        .read()
        .unwrap()
        .get(&plugin_id)
        .and_then(|p| {
            std::path::Path::new(p.path.as_ref())
                .file_stem()
                .map(|stem| stem.to_string_lossy().into_owned())
        });
    match name {
        Some(name) => format!("Plugin UI #{plugin_id} · {name}"),
        None => format!("Plugin UI #{plugin_id}"),
    }
}

impl BlaulichtApp {
    pub(crate) fn render_plugin_ui_contents(&self, ui: &mut egui::Ui, plugin_id: u8) {
        if matches!(
            self.data
                .state
                .plugin_runtime_kinds
                .read()
                .unwrap()
                .get(&plugin_id),
            Some(crate::state::PluginRuntimeKind::Animation { .. })
        ) {
            ui.label("Animation plugin UI is available in the animation editor.");
            return;
        }
        let ops = self
            .data
            .state
            .plugin_ui_ops
            .read()
            .unwrap()
            .get(&plugin_id)
            .cloned();

        if let Some(ops) = ops {
            let mut idx = 0usize;
            render_plugin_ops(ui, &ops, &mut idx, &self.data, plugin_id, None);
        } else {
            ui.label("No UI generated by plugin yet.");
        }
    }

    pub fn render_plugin_ui(&self, ctx: &Context, canvas_screen_id: ScreenId) {
        let ops_map = self.data.state.plugin_ui_ops.read().unwrap().clone();
        let visibility_map = self.data.state.plugin_ui_visibility.read().unwrap().clone();
        let popped_out_map = self.data.state.plugin_ui_popped_out.read().unwrap().clone();

        for (plugin_id, visibility) in visibility_map.iter() {
            if matches!(
                self.data
                    .state
                    .plugin_runtime_kinds
                    .read()
                    .unwrap()
                    .get(plugin_id),
                Some(crate::state::PluginRuntimeKind::Animation { .. })
            ) {
                continue;
            }
            let mut is_open = visibility.open;
            if !is_open {
                continue;
            }

            if visibility.screen_id != canvas_screen_id {
                continue;
            }

            let title = plugin_ui_title(&self.data, *plugin_id);
            let is_popped_out = *popped_out_map.get(plugin_id).unwrap_or(&false);

            if is_popped_out {
                let viewport_id = egui::ViewportId::from_hash_of(format!("plugin_{}", plugin_id));
                let plugin_id_copy = *plugin_id;
                let ops_copy = ops_map.get(plugin_id).cloned();
                let data_clone = self.data.clone();
                let maximize_requested = self
                    .data
                    .state
                    .plugin_ui_maximize_requested
                    .write()
                    .unwrap()
                    .remove(plugin_id)
                    .unwrap_or(false);

                let mut viewport = egui::ViewportBuilder::default()
                    .with_title(title.clone())
                    .with_inner_size([800.0, 600.0])
                    .with_resizable(true);

                if maximize_requested {
                    viewport = viewport.with_maximized(true);
                }

                ctx.show_viewport_immediate(viewport_id, viewport, move |ctx, _class| {
                    if maximize_requested {
                        ctx.send_viewport_cmd(egui::ViewportCommand::Maximized(true));
                    }

                    let mut pop_in_clicked = false;
                    egui::CentralPanel::default().show(ctx, |ui| {
                        ui.horizontal(|ui| {
                            if plugin_action(ui, "Pop in", true) {
                                pop_in_clicked = true;
                            }
                        });
                        ui.separator();

                        egui::ScrollArea::both()
                            .auto_shrink([false, false])
                            .stick_to_bottom(false)
                            .show(ui, |ui| {
                                if let Some(ref ops) = ops_copy {
                                    let mut idx = 0usize;
                                    render_plugin_ops(
                                        ui,
                                        ops,
                                        &mut idx,
                                        &data_clone,
                                        *plugin_id,
                                        None,
                                    );
                                } else {
                                    ui.label("No UI generated by plugin yet.");
                                }
                            });
                    });

                    if pop_in_clicked {
                        let mut map = data_clone.state.plugin_ui_popped_out.write().unwrap();
                        if let Some(v) = map.get_mut(&plugin_id_copy) {
                            *v = false;
                        }
                    }

                    if ctx.input(|i| i.viewport().close_requested()) {
                        let mut map = data_clone.state.plugin_ui_visibility.write().unwrap();
                        if let Some(v) = map.get_mut(&plugin_id_copy) {
                            v.open = false;

                            notify_plugin_ui_open(&data_clone, plugin_id_copy, false);
                        }
                    }
                });
            } else {
                let mut pop_out_clicked = false;
                egui::Window::new(&title)
                    .open(&mut is_open)
                    .default_size([560.0, 400.0])
                    .resizable(true)
                    .show(ctx, |ui| {
                        ui.horizontal(|ui| {
                            if plugin_action(ui, "Pop out", true) {
                                pop_out_clicked = true;
                            }
                        });
                        ui.separator();

                        egui::ScrollArea::both()
                            .auto_shrink([false, false])
                            .stick_to_bottom(false)
                            .show(ui, |ui| {
                                if let Some(ops) = ops_map.get(plugin_id) {
                                    let mut idx = 0usize;
                                    render_plugin_ops(
                                        ui, ops, &mut idx, &self.data, *plugin_id, None,
                                    );
                                } else {
                                    ui.label("No UI generated by plugin yet.");
                                }
                            });
                    });

                if pop_out_clicked {
                    let mut map = self.data.state.plugin_ui_popped_out.write().unwrap();
                    if let Some(v) = map.get_mut(plugin_id) {
                        *v = true;
                    }
                }

                if !is_open {
                    let mut map = self.data.state.plugin_ui_visibility.write().unwrap();
                    if let Some(v) = map.get_mut(plugin_id) {
                        v.open = false;
                        notify_plugin_ui_open(&self.data, *plugin_id, false);
                    }
                }
            }
        }
    }
}

/// Use the application's button geometry, expanding labels before truncating.
fn plugin_button_size(ui: &egui::Ui, label: &str) -> components::ButtonSize {
    let size = components::ButtonSize::Medium;
    let text_width = ui
        .painter()
        .layout_no_wrap(
            label.to_owned(),
            egui::FontId::proportional(size.dim().1),
            ui.visuals().text_color(),
        )
        .size()
        .x;
    size.with_width(
        (text_width + 24.0)
            .max(size.dim().0.x)
            .min(ui.max_rect().width().max(90.0)),
    )
}

fn plugin_action(ui: &mut egui::Ui, label: &str, enabled: bool) -> bool {
    let size = plugin_button_size(ui, label);
    components::action_button(ui, enabled, label, size, None)
}

/// Show a text field whose committed value comes from the plugin a tick late.
/// While the field has focus the text typed so far is kept in egui memory so
/// the plugin's stale echo cannot overwrite it mid-keystroke; once focus is
/// lost the plugin's value is shown again. Returns the new text when edited.
fn plugin_text_edit(
    ui: &mut egui::Ui,
    plugin_id: u8,
    animation_instance: Option<u64>,
    id: u8,
    text: &str,
    multiline: bool,
) -> Option<String> {
    let edit_id = ui.make_persistent_id((
        "plugin_text_edit",
        plugin_id,
        animation_instance,
        id,
        multiline,
    ));
    let has_focus = ui.memory(|m| m.has_focus(edit_id));
    let mut s = if has_focus {
        ui.data_mut(|d| {
            d.get_temp::<String>(edit_id)
                .unwrap_or_else(|| text.to_owned())
        })
    } else {
        text.to_owned()
    };

    let response = if multiline {
        ui.add(
            egui::TextEdit::multiline(&mut s)
                .id(edit_id)
                .desired_rows(3)
                .desired_width(300.0),
        )
    } else {
        ui.add(egui::TextEdit::singleline(&mut s).id(edit_id))
    };

    ui.data_mut(|d| d.insert_temp(edit_id, s.clone()));
    response.changed().then_some(s)
}

/// Render `ops` starting at `idx` until the ops run out or a matching `End*`
/// op returns from the current nesting level. Callers bound nested content by
/// passing a shorter slice (`&ops[..end]`); indexes stay relative to the full
/// op list.
pub(crate) fn render_plugin_ops(
    ui: &mut egui::Ui,
    ops: &[crate::ui_ops::WasmUiOp],
    idx: &mut usize,
    data: &crate::state::AppStateWrapper,
    plugin_id: u8,
    animation_instance: Option<u64>,
) {
    use crate::ui_ops::WasmUiOp as Op;
    let route_event = |event| match animation_instance {
        Some(instance) => ControlEvent::AnimationPluginUi(event, plugin_id, instance),
        None => ControlEvent::PluginUi(event, plugin_id),
    };
    while *idx < ops.len() {
        match &ops[*idx] {
            Op::Label(text) => {
                ui.label(text);
                *idx += 1;
            }
            Op::LabelStyled {
                text,
                size,
                monospace,
            } => {
                let mut rich = egui::RichText::new(text).size(*size as f32);
                if *monospace {
                    rich = rich.monospace();
                }
                ui.label(rich);
                *idx += 1;
            }
            Op::SetMaxWidth { width } => {
                if *width > 0 {
                    ui.set_max_width(*width as f32);
                }
                *idx += 1;
            }
            Op::SetMinWidth { width } => {
                if *width >= 0 {
                    ui.set_min_width(*width as f32);
                }
                *idx += 1;
            }
            Op::Separator => {
                ui.separator();
                *idx += 1;
            }
            Op::Button { label, id } => {
                if plugin_action(ui, label, true) {
                    let evt = route_event(PluginUiEvent::Button { id: *id });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::ButtonStyled { label, id, enabled } => {
                let clicked = plugin_action(ui, label, *enabled);
                if *enabled && clicked {
                    let evt = route_event(PluginUiEvent::Button { id: *id });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::ComboBox {
                label,
                id,
                options,
                selected,
            } => {
                let combo_id = ui.make_persistent_id(format!("plugin_combo_{}_{}", plugin_id, id));
                let mut current = *selected;
                let mut changed = false;
                let selected_text = options
                    .get(current as usize)
                    .map(|s| s.as_str())
                    .unwrap_or("<none>");
                ui.horizontal(|ui| {
                    if !label.is_empty() {
                        ui.label(label);
                    }
                    egui::ComboBox::from_id_salt(combo_id)
                        .selected_text(selected_text)
                        .show_ui(ui, |ui| {
                            for (idx_opt, label) in options.iter().enumerate() {
                                if ui
                                    .selectable_value(&mut current, idx_opt as u8, label)
                                    .changed()
                                {
                                    changed = true;
                                }
                            }
                        });
                });

                if changed {
                    let evt = route_event(PluginUiEvent::ComboBox {
                        id: *id,
                        selected: current,
                    });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::Checkbox { label, id, checked } => {
                let mut c = *checked;
                if ui.checkbox(&mut c, label).changed() {
                    let evt = route_event(PluginUiEvent::Checkbox {
                        id: *id,
                        checked: c,
                    });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::Switch { label, id, value } => {
                let mut state = *value;
                let mut widget = components::Switch::new(&mut state);
                if !label.is_empty() {
                    widget = widget.with_label(label.clone());
                }

                if ui.add(widget).changed() {
                    let evt = route_event(PluginUiEvent::Switch {
                        id: *id,
                        value: state,
                    });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }

                *idx += 1;
            }
            Op::Slider {
                label,
                id,
                min,
                max,
                value,
            } => {
                let mut v = *value;
                if ui
                    .add(egui::Slider::new(&mut v, (*min)..=(*max)).text(label))
                    .changed()
                {
                    let evt = route_event(PluginUiEvent::Slider { id: *id, value: v });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::HFader {
                label,
                id,
                min,
                max,
                value,
            } => {
                let mut current = *value as f32;
                let mut widget =
                    components::HFader::new(&mut current, (*min as f32)..=(*max as f32));
                if !label.is_empty() {
                    widget = widget.with_label(label.clone());
                }

                if ui.add(widget).changed() {
                    let new_value = current.round().clamp(*min as f32, *max as f32) as u8;
                    let evt = route_event(PluginUiEvent::HFader {
                        id: *id,
                        value: new_value,
                    });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }

                *idx += 1;
            }
            Op::TextEdit { label, id, text } => {
                let response = ui.horizontal(|ui| {
                    if !label.is_empty() {
                        ui.label(label);
                    }
                    plugin_text_edit(ui, plugin_id, animation_instance, *id, text, false)
                });
                if let Some(text) = response.inner {
                    let evt = route_event(PluginUiEvent::Text { id: *id, text });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::TextEditMultiline { label, id, text } => {
                if !label.is_empty() {
                    ui.label(label);
                }
                if let Some(text) =
                    plugin_text_edit(ui, plugin_id, animation_instance, *id, text, true)
                {
                    let evt = route_event(PluginUiEvent::Text { id: *id, text });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::ColorPicker { id, r, g, b, a } => {
                let mut color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                if ui.color_edit_button_srgba(&mut color).changed() {
                    let [r, g, b, a] = color.to_srgba_unmultiplied();
                    let evt = route_event(PluginUiEvent::Color {
                        id: *id,
                        r,
                        g,
                        b,
                        a,
                    });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::BeginFrame { id: _ } => {
                *idx += 1;
                ui.group(|ui| {
                    render_plugin_ops(ui, ops, idx, data, plugin_id, animation_instance);
                });
            }
            Op::BeginFrameStyled {
                id: _,
                title,
                pad_x,
                pad_y,
                margin_x,
                margin_y,
            } => {
                *idx += 1;
                egui::Frame::group(ui.style())
                    .inner_margin(egui::Margin::symmetric(
                        (*pad_x).clamp(0, 127) as i8,
                        (*pad_y).clamp(0, 127) as i8,
                    ))
                    .outer_margin(egui::Margin::symmetric(
                        (*margin_x).clamp(0, 127) as i8,
                        (*margin_y).clamp(0, 127) as i8,
                    ))
                    .show(ui, |ui| {
                        ui.vertical(|ui| {
                            if !title.is_empty() {
                                ui.label(egui::RichText::new(title).strong());
                                ui.separator();
                            }
                            render_plugin_ops(ui, ops, idx, data, plugin_id, animation_instance);
                        });
                    });
            }
            Op::BeginFrameStyledBorder {
                id: _,
                title,
                pad_x,
                pad_y,
                margin_x,
                margin_y,
                border_r,
                border_g,
                border_b,
                border_a,
                border_thickness,
            } => {
                *idx += 1;
                let stroke = egui::Stroke::new(
                    (*border_thickness).max(0) as f32,
                    egui::Color32::from_rgba_unmultiplied(
                        *border_r, *border_g, *border_b, *border_a,
                    ),
                );
                egui::Frame::group(ui.style())
                    .stroke(stroke)
                    .inner_margin(egui::Margin::symmetric(
                        (*pad_x).clamp(0, 127) as i8,
                        (*pad_y).clamp(0, 127) as i8,
                    ))
                    .outer_margin(egui::Margin::symmetric(
                        (*margin_x).clamp(0, 127) as i8,
                        (*margin_y).clamp(0, 127) as i8,
                    ))
                    .show(ui, |ui| {
                        ui.vertical(|ui| {
                            if !title.is_empty() {
                                ui.label(egui::RichText::new(title).strong());
                                ui.separator();
                            }
                            render_plugin_ops(ui, ops, idx, data, plugin_id, animation_instance);
                        });
                    });
            }
            Op::EndFrame => {
                *idx += 1;
                return;
            }
            Op::BeginCollapsing {
                id,
                title,
                default_open,
            } => {
                *idx += 1;
                let response = egui::CollapsingHeader::new(title)
                    .id_salt(("plugin_collapsing", plugin_id, animation_instance, *id))
                    .default_open(*default_open)
                    .show(ui, |ui| {
                        render_plugin_ops(ui, ops, idx, data, plugin_id, animation_instance);
                    });
                if response.body_returned.is_none() {
                    // Collapsed: egui skipped the body, so its ops are still
                    // unconsumed. Skip to the matching EndCollapsing, or the
                    // hidden content would render outside the header and its
                    // EndCollapsing would end the enclosing container early.
                    let mut depth = 1usize;
                    while *idx < ops.len() && depth > 0 {
                        match ops[*idx] {
                            Op::BeginCollapsing { .. } => depth += 1,
                            Op::EndCollapsing => depth -= 1,
                            _ => {}
                        }
                        *idx += 1;
                    }
                }
            }
            Op::EndCollapsing => {
                *idx += 1;
                return;
            }
            Op::BeginTabs { id } => {
                // Collect tabs metadata: (tab id, title, content start, content end).
                *idx += 1;
                let mut tabs: Vec<(u8, String, usize, usize)> = Vec::new();
                let mut scan = *idx;
                let mut end_tabs = ops.len();
                while scan < ops.len() {
                    match &ops[scan] {
                        Op::BeginTab {
                            tabs_id,
                            tab_id,
                            title,
                        } if tabs_id == id => {
                            let tab_start = scan + 1;
                            scan += 1;
                            let mut depth = 1;
                            while scan < ops.len() && depth > 0 {
                                match &ops[scan] {
                                    Op::BeginTab { .. } => depth += 1,
                                    Op::EndTab => depth -= 1,
                                    _ => {}
                                }
                                scan += 1;
                            }
                            // `scan` is just past this tab's EndTab.
                            let tab_end = scan.saturating_sub(1).max(tab_start);
                            tabs.push((*tab_id, title.clone(), tab_start, tab_end));
                        }
                        Op::EndTabs => {
                            end_tabs = scan;
                            break;
                        }
                        _ => scan += 1,
                    }
                }

                // Current selection, keyed per plugin so two plugins using the
                // same tabs id do not share one selection. The lock is released
                // before rendering: tab content may itself contain tab groups.
                let key = (plugin_id, *id);
                let default_tab = tabs.first().map(|t| t.0).unwrap_or(0);
                let mut current = {
                    let mut sel_map = data.state.plugin_ui_tabs_selected.write().unwrap();
                    *sel_map.entry(key).or_insert(default_tab)
                };
                if !tabs.iter().any(|(tid, _, _, _)| *tid == current) {
                    current = default_tab;
                }

                // Tab header; wraps so many tabs stay reachable in a narrow window.
                let mut selection_changed = false;
                ui.horizontal_wrapped(|ui| {
                    for (tab_id, title, _, _) in &tabs {
                        let size = plugin_button_size(ui, title);
                        let clicked = components::button(ui, current == *tab_id, title, size);
                        if clicked && current != *tab_id {
                            current = *tab_id;
                            selection_changed = true;
                        }
                    }
                });

                ui.separator();

                if selection_changed {
                    data.state
                        .plugin_ui_tabs_selected
                        .write()
                        .unwrap()
                        .insert(key, current);
                    let evt = route_event(PluginUiEvent::TabChanged {
                        tabs_id: *id,
                        tab_id: current,
                    });
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }

                // Render only the selected tab's content, bounded to its EndTab.
                if let Some((_, _, s, e)) = tabs.iter().find(|(tid, _, _, _)| *tid == current) {
                    let mut inner_idx = *s;
                    let bounded = &ops[..*e];
                    while inner_idx < *e {
                        render_plugin_ops(
                            ui,
                            bounded,
                            &mut inner_idx,
                            data,
                            plugin_id,
                            animation_instance,
                        );
                    }
                }

                // Continue after this group's EndTabs.
                *idx = (end_tabs + 1).min(ops.len());
            }
            Op::BeginTab { .. } | Op::EndTab | Op::EndTabs => {
                // Should be handled in BeginTabs
                *idx += 1;
            }
            Op::BeginVertical => {
                *idx += 1;
                ui.vertical(|ui| {
                    render_plugin_ops(ui, ops, idx, data, plugin_id, animation_instance);
                });
            }
            Op::EndVertical => {
                *idx += 1;
                return;
            }
            Op::BeginHorizontal => {
                *idx += 1;
                // Wrap so rows of buttons stay reachable on the 800x480 panel
                // instead of running past the window edge.
                ui.horizontal_wrapped(|ui| {
                    render_plugin_ops(ui, ops, idx, data, plugin_id, animation_instance);
                });
            }
            Op::EndHorizontal => {
                *idx += 1;
                return;
            }
            Op::PainterBegin { id, width, height } if *width <= 0 || *height <= 0 => {
                // Degenerate canvas: skip its drawing ops instead of dividing by zero.
                *idx += 1;
                while *idx < ops.len() && !matches!(ops[*idx], Op::PainterEnd) {
                    *idx += 1;
                }
                *idx = (*idx + 1).min(ops.len());
                let _ = id;
            }
            Op::PainterBegin { id, width, height } => {
                *idx += 1;
                // Keep the requested aspect ratio, but fit the canvas to the pane.
                // Pointer coordinates below are converted back to plugin coordinates.
                let canvas_width = ui.available_width().max(1.0).min(*width as f32);
                let scaled_size =
                    egui::vec2(canvas_width, canvas_width * *height as f32 / *width as f32);
                let (rect, resp) =
                    ui.allocate_exact_size(scaled_size, egui::Sense::click_and_drag());
                tracing::debug!("[Host] PainterBegin: allocated rect={:?}", rect);

                let scale_x = *width as f32 / scaled_size.x;
                let scale_y = *height as f32 / scaled_size.y;

                if resp.clicked() {
                    if let Some(pos) = resp.interact_pointer_pos() {
                        let local_pos = pos - rect.min;
                        let evt = route_event(PluginUiEvent::CanvasClick {
                            id: *id,
                            x: (local_pos.x * scale_x) as i32,
                            y: (local_pos.y * scale_y) as i32,
                        });
                        data.event_bus_connection
                            .send(ControlEventMessage::new(EventOriginator::Web, evt));
                    }
                }

                if resp.dragged() {
                    if let Some(pos) = resp.interact_pointer_pos() {
                        let local_pos = pos - rect.min;
                        let delta = resp.drag_delta();
                        let evt = route_event(PluginUiEvent::CanvasDrag {
                            id: *id,
                            x: (local_pos.x * scale_x) as i32,
                            y: (local_pos.y * scale_y) as i32,
                            dx: (delta.x * scale_x) as i32,
                            dy: (delta.y * scale_y) as i32,
                        });
                        data.event_bus_connection
                            .send(ControlEventMessage::new(EventOriginator::Web, evt));
                    }
                }

                let multi_touch = ui.input(|i| i.multi_touch());
                if let Some(zoom_delta) = multi_touch {
                    let zoom = zoom_delta.zoom_delta;
                    if zoom != 1.0 {
                        if let Some(pos) = resp.hover_pos() {
                            let local_pos = pos - rect.min;
                            let evt = route_event(PluginUiEvent::CanvasPinch {
                                id: *id,
                                x: (local_pos.x * scale_x) as i32,
                                y: (local_pos.y * scale_y) as i32,
                                delta: zoom - 1.0,
                            });
                            data.event_bus_connection
                                .send(ControlEventMessage::new(EventOriginator::Web, evt));
                        }
                    }
                }

                let painter = ui.painter_at(rect);
                let render_scale_x = scaled_size.x / *width as f32;
                let render_scale_y = scaled_size.y / *height as f32;

                while *idx < ops.len() {
                    match &ops[*idx] {
                        Op::PainterRect {
                            x,
                            y,
                            w,
                            h,
                            r,
                            g,
                            b,
                            a,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            let rct = egui::Rect::from_min_size(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                egui::vec2(*w as f32 * render_scale_x, *h as f32 * render_scale_y),
                            );
                            painter.rect_filled(rct, 0.0, color);
                            *idx += 1;
                        }
                        Op::PainterCircle {
                            x,
                            y,
                            radius,
                            r,
                            g,
                            b,
                            a,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            painter.circle_filled(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                *radius as f32 * render_scale_x.min(render_scale_y),
                                color,
                            );
                            *idx += 1;
                        }
                        Op::PainterLine {
                            x1,
                            y1,
                            x2,
                            y2,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            painter.line_segment(
                                [
                                    rect.min
                                        + egui::vec2(
                                            *x1 as f32 * render_scale_x,
                                            *y1 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *x2 as f32 * render_scale_x,
                                            *y2 as f32 * render_scale_y,
                                        ),
                                ],
                                egui::Stroke::new((*thickness).max(1) as f32, color),
                            );
                            *idx += 1;
                        }
                        Op::PainterText {
                            x,
                            y,
                            size,
                            r,
                            g,
                            b,
                            a,
                            text,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            painter.text(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                egui::Align2::LEFT_TOP,
                                text,
                                egui::FontId::proportional(
                                    (*size).max(8) as f32 * render_scale_x.min(render_scale_y),
                                ),
                                color,
                            );
                            *idx += 1;
                        }
                        Op::PainterEnd => {
                            *idx += 1;
                            break;
                        }
                        Op::PainterRectStroke {
                            x,
                            y,
                            w,
                            h,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            let rct = egui::Rect::from_min_size(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                egui::vec2(*w as f32 * render_scale_x, *h as f32 * render_scale_y),
                            );
                            painter.rect_stroke(
                                rct,
                                0.0,
                                egui::Stroke::new((*thickness).max(1) as f32, color),
                                egui::StrokeKind::Middle,
                            );
                            *idx += 1;
                        }
                        Op::PainterCircleStroke {
                            x,
                            y,
                            radius,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            painter.circle_stroke(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                *radius as f32 * render_scale_x.min(render_scale_y),
                                egui::Stroke::new((*thickness).max(1) as f32, color),
                            );
                            *idx += 1;
                        }
                        Op::PainterCubicBezier {
                            x1,
                            y1,
                            cx1,
                            cy1,
                            cx2,
                            cy2,
                            x2,
                            y2,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_unmultiplied(*r, *g, *b, *a);
                            let shape = egui::epaint::CubicBezierShape {
                                points: [
                                    rect.min
                                        + egui::vec2(
                                            *x1 as f32 * render_scale_x,
                                            *y1 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *cx1 as f32 * render_scale_x,
                                            *cy1 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *cx2 as f32 * render_scale_x,
                                            *cy2 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *x2 as f32 * render_scale_x,
                                            *y2 as f32 * render_scale_y,
                                        ),
                                ],
                                closed: false,
                                fill: egui::Color32::TRANSPARENT,
                                stroke: egui::epaint::PathStroke::new(
                                    (*thickness).max(1) as f32,
                                    color,
                                ),
                            };
                            painter.add(shape);
                            *idx += 1;
                        }
                        _ => {
                            // Unexpected op inside painter - stop painter
                            break;
                        }
                    }
                }
            }
            Op::PainterRect { .. }
            | Op::PainterCircle { .. }
            | Op::PainterLine { .. }
            | Op::PainterText { .. }
            | Op::PainterRectStroke { .. }
            | Op::PainterCircleStroke { .. }
            | Op::PainterCubicBezier { .. }
            | Op::PainterEnd => {
                // These should be consumed within PainterBegin; skip to avoid infinite loop
                *idx += 1;
            }
        }
    }
}
