use crate::app::components::ButtonSize;
use crate::app::{components, theme, AppPage, BlaulichtApp, PopupSpec};
use crate::{msg::SystemMessage, state::AppStateWrapper};
use blaulicht_shared::{
    ControlEvent, ControlEventMessage, EventOriginator, LogLevel, MainUiEvent, PluginUiEvent,
};
use crossbeam_channel::TryRecvError;
use egui::Context;
use strum::IntoEnumIterator;

#[cfg(feature = "audio")]
use cpal::traits::DeviceTrait;

impl BlaulichtApp {
    pub fn render_plugin_ui(&self, ctx: &Context) {
        let ops_map = self.data.state.plugin_ui_ops.read().unwrap().clone();
        let visibility_map = self.data.state.plugin_ui_visibility.read().unwrap().clone();
        let popped_out_map = self.data.state.plugin_ui_popped_out.read().unwrap().clone();

        for (plugin_id, visible) in visibility_map.iter() {
            let mut is_open = *visible;
            if !is_open {
                continue;
            }

            let title = format!("Plugin UI #{plugin_id}");
            let is_popped_out = *popped_out_map.get(plugin_id).unwrap_or(&false);

            if is_popped_out {
                let viewport_id = egui::ViewportId::from_hash_of(format!("plugin_{}", plugin_id));
                let plugin_id_copy = *plugin_id;
                let ops_copy = ops_map.get(plugin_id).cloned();
                let data_clone = self.data.clone();

                ctx.show_viewport_immediate(
                    viewport_id,
                    egui::ViewportBuilder::default()
                        .with_title(title.clone())
                        .with_inner_size([800.0, 600.0])
                        .with_resizable(true),
                    move |ctx, _class| {
                        let mut pop_in_clicked = false;
                        egui::CentralPanel::default().show(ctx, |ui| {
                            ui.horizontal(|ui| {
                                if ui.button("🗗 Pop In").clicked() {
                                    pop_in_clicked = true;
                                }
                            });
                            ui.separator();

                            egui::ScrollArea::both()
                                .auto_shrink([false, false])
                                .stick_to_bottom(false)
                                .show(ui, |ui| {
                                    if let Some(ref ops) = ops_copy {
                                        let mut idx = 0usize;
                                        render_plugin_ops(
                                            ui,
                                            ops,
                                            &mut idx,
                                            &data_clone,
                                            *plugin_id,
                                        );
                                    } else {
                                        ui.label("No UI generated by plugin yet.");
                                    }
                                });
                        });

                        if pop_in_clicked {
                            let mut map = data_clone.state.plugin_ui_popped_out.write().unwrap();
                            if let Some(v) = map.get_mut(&plugin_id_copy) {
                                *v = false;
                            }
                        }

                        if ctx.input(|i| i.viewport().close_requested()) {
                            let mut map = data_clone.state.plugin_ui_visibility.write().unwrap();
                            if let Some(v) = map.get_mut(&plugin_id_copy) {
                                *v = false;

                                // Notify plugins.
                                self.data
                                    .event_bus_connection
                                    .send(ControlEventMessage::new(
                                        EventOriginator::Web,
                                        ControlEvent::MainUi(MainUiEvent::SetPluginUIOpen {
                                            plugin_id: plugin_id_copy,
                                            open: false,
                                        }),
                                    ));
                            }
                        }
                    },
                );
            } else {
                let mut pop_out_clicked = false;
                egui::Window::new(&title)
                    .open(&mut is_open)
                    .resizable(true)
                    .show(ctx, |ui| {
                        ui.horizontal(|ui| {
                            if ui.button("🗗 Pop Out").clicked() {
                                pop_out_clicked = true;
                            }
                        });
                        ui.separator();

                        egui::ScrollArea::both()
                            .auto_shrink([false, false])
                            .stick_to_bottom(false)
                            .show(ui, |ui| {
                                if let Some(ops) = ops_map.get(plugin_id) {
                                    let mut idx = 0usize;
                                    render_plugin_ops(ui, ops, &mut idx, &self.data, *plugin_id);
                                } else {
                                    ui.label("No UI generated by plugin yet.");
                                }
                            });
                    });

                if pop_out_clicked {
                    let mut map = self.data.state.plugin_ui_popped_out.write().unwrap();
                    if let Some(v) = map.get_mut(plugin_id) {
                        *v = true;
                    }
                }

                if !is_open {
                    let mut map = self.data.state.plugin_ui_visibility.write().unwrap();
                    if let Some(v) = map.get_mut(plugin_id) {
                        *v = false;
                    }
                }
            }
        }
    }
}

fn render_plugin_ops(
    ui: &mut egui::Ui,
    ops: &Vec<crate::ui_ops::WasmUiOp>,
    idx: &mut usize,
    data: &crate::state::AppStateWrapper,
    plugin_id: u8,
) {
    use crate::ui_ops::WasmUiOp as Op;
    while *idx < ops.len() {
        match &ops[*idx] {
            Op::Label(text) => {
                ui.label(text);
                *idx += 1;
            }
            Op::Separator => {
                ui.separator();
                *idx += 1;
            }
            Op::Button { label, id } => {
                if ui.button(label).clicked() {
                    let evt = ControlEvent::PluginUi(PluginUiEvent::Button { id: *id }, plugin_id);
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::Checkbox { label, id, checked } => {
                let mut c = *checked;
                if ui.checkbox(&mut c, label).changed() {
                    let evt = ControlEvent::PluginUi(
                        PluginUiEvent::Checkbox {
                            id: *id,
                            checked: c,
                        },
                        plugin_id,
                    );
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::Slider {
                label,
                id,
                min,
                max,
                value,
            } => {
                let mut v = *value;
                if ui
                    .add(egui::Slider::new(&mut v, (*min)..=(*max)).text(label))
                    .changed()
                {
                    let evt = ControlEvent::PluginUi(
                        PluginUiEvent::Slider { id: *id, value: v },
                        plugin_id,
                    );
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::TextEdit { label, id, text } => {
                let edit_id = ui.make_persistent_id(format!("text_edit_{}", id));
                let mut s = ui.data_mut(|d| {
                    d.get_temp::<String>(edit_id)
                        .unwrap_or_else(|| text.clone())
                });

                let response = ui.text_edit_singleline(&mut s);

                ui.data_mut(|d| d.insert_temp(edit_id, s.clone()));

                if response.changed() {
                    let evt =
                        ControlEvent::PluginUi(PluginUiEvent::Text { id: *id, text: s }, plugin_id);
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                } else if !response.has_focus() {
                    ui.label(label);
                }
                *idx += 1;
            }
            Op::TextEditMultiline { label: _, id, text } => {
                let mut s = text.clone();
                let resp = ui.add(
                    egui::TextEdit::multiline(&mut s)
                        .desired_rows(3)
                        .desired_width(300.0),
                );
                if resp.changed() {
                    let evt =
                        ControlEvent::PluginUi(PluginUiEvent::Text { id: *id, text: s }, plugin_id);
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::ColorPicker { id, r, g, b, a } => {
                let mut color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                if ui.color_edit_button_srgba(&mut color).changed() {
                    let [r, g, b, a] = color.to_array();
                    let evt = ControlEvent::PluginUi(
                        PluginUiEvent::Color {
                            id: *id,
                            r,
                            g,
                            b,
                            a,
                        },
                        plugin_id,
                    );
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }
                *idx += 1;
            }
            Op::BeginFrame { id: _ } => {
                *idx += 1;
                ui.group(|ui| {
                    render_plugin_ops(ui, ops, idx, data, plugin_id);
                });
            }
            Op::BeginFrameStyled {
                id: _,
                title,
                pad_x,
                pad_y,
                margin_x,
                margin_y,
            } => {
                *idx += 1;
                let px = (*pad_x).max(0) as f32;
                let py = (*pad_y).max(0) as f32;
                let mx = (*margin_x).max(0) as f32;
                let my = (*margin_y).max(0) as f32;
                // Outer margins (vertical)
                if my > 0.0 {
                    ui.add_space(my);
                }
                egui::Frame::group(ui.style()).show(ui, |ui| {
                    // Inner padding via spaces
                    ui.add_space(py);
                    ui.horizontal(|ui| {
                        if px > 0.0 {
                            ui.add_space(px);
                        }
                        ui.vertical(|ui| {
                            ui.label(egui::RichText::new(title).strong());
                            ui.separator();
                            render_plugin_ops(ui, ops, idx, data, plugin_id);
                        });
                        if px > 0.0 {
                            ui.add_space(px);
                        }
                    });
                    ui.add_space(py);
                });
                if my > 0.0 {
                    ui.add_space(my);
                }
            }
            Op::EndFrame => {
                *idx += 1;
                return;
            }
            Op::BeginCollapsing {
                id: _,
                title,
                default_open,
            } => {
                *idx += 1;
                egui::CollapsingHeader::new(title)
                    .default_open(*default_open)
                    .show(ui, |ui| {
                        render_plugin_ops(ui, ops, idx, data, plugin_id);
                    });
            }
            Op::EndCollapsing => {
                *idx += 1;
                return;
            }
            Op::BeginTabs { id } => {
                // Collect tabs metadata
                *idx += 1;
                let start = *idx;
                let mut tabs: Vec<(u8, String, usize, usize)> = Vec::new();
                let mut scan = start;
                while scan < ops.len() {
                    match &ops[scan] {
                        Op::BeginTab {
                            tabs_id,
                            tab_id,
                            title,
                        } if tabs_id == id => {
                            let tab_start = scan + 1;
                            // find EndTab
                            scan += 1;
                            let mut depth = 1;
                            while scan < ops.len() && depth > 0 {
                                match &ops[scan] {
                                    Op::BeginTab {
                                        tabs_id: _,
                                        tab_id: _,
                                        title: _,
                                    } => depth += 1,
                                    Op::EndTab => depth -= 1,
                                    _ => {}
                                }
                                scan += 1;
                            }
                            let tab_end = scan - 1; // EndTab consumed in loop
                            tabs.push((*tab_id, title.clone(), tab_start, tab_end));
                        }
                        Op::EndTabs => break,
                        _ => scan += 1,
                    }
                }

                // Current selection
                let mut sel_map = data.state.plugin_ui_tabs_selected.write().unwrap();
                let current = sel_map
                    .entry((0, *id))
                    .or_insert_with(|| tabs.get(0).map(|t| t.0).unwrap_or(0));

                // Render tab header
                let mut selection_changed = false;
                ui.horizontal(|ui| {
                    for (tab_id, title, _, _) in &tabs {
                        let clicked = ui.selectable_label(*current == *tab_id, title).clicked();
                        if clicked && *current != *tab_id {
                            *current = *tab_id;
                            selection_changed = true;
                        }
                    }
                });

                ui.separator();

                // Emit selection change event
                if selection_changed {
                    let evt = ControlEvent::PluginUi(
                        PluginUiEvent::TabChanged {
                            tabs_id: *id,
                            tab_id: *current,
                        },
                        plugin_id,
                    );
                    data.event_bus_connection
                        .send(ControlEventMessage::new(EventOriginator::Web, evt));
                }

                // Render selected tab content
                if let Some((_, _, s, e)) = tabs.iter().find(|(tid, _, _, _)| tid == current) {
                    let mut inner_idx = *s;
                    while inner_idx < *e {
                        render_plugin_ops(ui, ops, &mut inner_idx, data, plugin_id);
                    }
                    *idx = *e; // position at end of inner
                }

                // Advance idx to after EndTabs
                while *idx < ops.len() {
                    if matches!(ops[*idx], Op::EndTabs) {
                        *idx += 1;
                        break;
                    }
                    *idx += 1;
                }
            }
            Op::BeginTab { .. } | Op::EndTab | Op::EndTabs => {
                // Should be handled in BeginTabs
                *idx += 1;
            }
            Op::BeginVertical => {
                *idx += 1;
                ui.vertical(|ui| {
                    render_plugin_ops(ui, ops, idx, data, plugin_id);
                });
            }
            Op::EndVertical => {
                *idx += 1;
                return;
            }
            Op::BeginHorizontal => {
                *idx += 1;
                ui.horizontal(|ui| {
                    render_plugin_ops(ui, ops, idx, data, plugin_id);
                });
            }
            Op::EndHorizontal => {
                *idx += 1;
                return;
            }
            Op::PainterBegin { id, width, height } => {
                *idx += 1;
                let available_size = ui.available_size();
                println!(
                    "[Host] PainterBegin: canvas_id={}, requested={}x{}, available={:?}",
                    id, width, height, available_size
                );

                // Use the requested dimensions if available_size is too small or zero
                let effective_available = egui::vec2(
                    available_size.x.max(*width as f32),
                    available_size.y.max(*height as f32),
                );

                let aspect_ratio = *width as f32 / *height as f32;
                let scaled_size = if effective_available.x / effective_available.y > aspect_ratio {
                    egui::vec2(effective_available.y * aspect_ratio, effective_available.y)
                } else {
                    egui::vec2(effective_available.x, effective_available.x / aspect_ratio)
                };
                println!(
                    "[Host] PainterBegin: scaled_size={:?}, rect will be allocated",
                    scaled_size
                );
                let (rect, resp) =
                    ui.allocate_exact_size(scaled_size, egui::Sense::click_and_drag());
                println!("[Host] PainterBegin: allocated rect={:?}", rect);

                let scale_x = *width as f32 / scaled_size.x;
                let scale_y = *height as f32 / scaled_size.y;

                if resp.clicked() {
                    if let Some(pos) = resp.interact_pointer_pos() {
                        let local_pos = pos - rect.min;
                        let evt = ControlEvent::PluginUi(
                            PluginUiEvent::CanvasClick {
                                id: *id,
                                x: (local_pos.x * scale_x) as i32,
                                y: (local_pos.y * scale_y) as i32,
                            },
                            plugin_id,
                        );
                        data.event_bus_connection
                            .send(ControlEventMessage::new(EventOriginator::Web, evt));
                    }
                }

                if resp.dragged() {
                    if let Some(pos) = resp.interact_pointer_pos() {
                        let local_pos = pos - rect.min;
                        let delta = resp.drag_delta();
                        let evt = ControlEvent::PluginUi(
                            PluginUiEvent::CanvasDrag {
                                id: *id,
                                x: (local_pos.x * scale_x) as i32,
                                y: (local_pos.y * scale_y) as i32,
                                dx: (delta.x * scale_x) as i32,
                                dy: (delta.y * scale_y) as i32,
                            },
                            plugin_id,
                        );
                        data.event_bus_connection
                            .send(ControlEventMessage::new(EventOriginator::Web, evt));
                    }
                }

                let multi_touch = ui.input(|i| i.multi_touch());
                if let Some(zoom_delta) = multi_touch {
                    let zoom = zoom_delta.zoom_delta;
                    if zoom != 1.0 {
                        if let Some(pos) = resp.hover_pos() {
                            let local_pos = pos - rect.min;
                            let evt = ControlEvent::PluginUi(
                                PluginUiEvent::CanvasPinch {
                                    id: *id,
                                    x: (local_pos.x * scale_x) as i32,
                                    y: (local_pos.y * scale_y) as i32,
                                    delta: zoom - 1.0,
                                },
                                plugin_id,
                            );
                            data.event_bus_connection
                                .send(ControlEventMessage::new(EventOriginator::Web, evt));
                        }
                    }
                }

                let painter = ui.painter_at(rect);
                let render_scale_x = scaled_size.x / *width as f32;
                let render_scale_y = scaled_size.y / *height as f32;

                while *idx < ops.len() {
                    match &ops[*idx] {
                        Op::PainterRect {
                            x,
                            y,
                            w,
                            h,
                            r,
                            g,
                            b,
                            a,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            let rct = egui::Rect::from_min_size(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                egui::vec2(*w as f32 * render_scale_x, *h as f32 * render_scale_y),
                            );
                            painter.rect_filled(rct, 0.0, color);
                            *idx += 1;
                        }
                        Op::PainterCircle {
                            x,
                            y,
                            radius,
                            r,
                            g,
                            b,
                            a,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            painter.circle_filled(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                *radius as f32 * render_scale_x.min(render_scale_y),
                                color,
                            );
                            *idx += 1;
                        }
                        Op::PainterLine {
                            x1,
                            y1,
                            x2,
                            y2,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            painter.line_segment(
                                [
                                    rect.min
                                        + egui::vec2(
                                            *x1 as f32 * render_scale_x,
                                            *y1 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *x2 as f32 * render_scale_x,
                                            *y2 as f32 * render_scale_y,
                                        ),
                                ],
                                egui::Stroke::new((*thickness).max(1) as f32, color),
                            );
                            *idx += 1;
                        }
                        Op::PainterText {
                            x,
                            y,
                            size,
                            r,
                            g,
                            b,
                            a,
                            text,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            painter.text(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                egui::Align2::LEFT_TOP,
                                text,
                                egui::FontId::proportional(
                                    (*size).max(8) as f32 * render_scale_x.min(render_scale_y),
                                ),
                                color,
                            );
                            *idx += 1;
                        }
                        Op::PainterEnd => {
                            *idx += 1;
                            break;
                        }
                        Op::PainterRectStroke {
                            x,
                            y,
                            w,
                            h,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            let rct = egui::Rect::from_min_size(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                egui::vec2(*w as f32 * render_scale_x, *h as f32 * render_scale_y),
                            );
                            painter.rect_stroke(
                                rct,
                                0.0,
                                egui::Stroke::new((*thickness).max(1) as f32, color),
                                egui::StrokeKind::Middle,
                            );
                            *idx += 1;
                        }
                        Op::PainterCircleStroke {
                            x,
                            y,
                            radius,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            painter.circle_stroke(
                                rect.min
                                    + egui::vec2(
                                        *x as f32 * render_scale_x,
                                        *y as f32 * render_scale_y,
                                    ),
                                *radius as f32 * render_scale_x.min(render_scale_y),
                                egui::Stroke::new((*thickness).max(1) as f32, color),
                            );
                            *idx += 1;
                        }
                        Op::PainterCubicBezier {
                            x1,
                            y1,
                            cx1,
                            cy1,
                            cx2,
                            cy2,
                            x2,
                            y2,
                            r,
                            g,
                            b,
                            a,
                            thickness,
                        } => {
                            let color = egui::Color32::from_rgba_premultiplied(*r, *g, *b, *a);
                            let shape = egui::epaint::CubicBezierShape {
                                points: [
                                    rect.min
                                        + egui::vec2(
                                            *x1 as f32 * render_scale_x,
                                            *y1 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *cx1 as f32 * render_scale_x,
                                            *cy1 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *cx2 as f32 * render_scale_x,
                                            *cy2 as f32 * render_scale_y,
                                        ),
                                    rect.min
                                        + egui::vec2(
                                            *x2 as f32 * render_scale_x,
                                            *y2 as f32 * render_scale_y,
                                        ),
                                ],
                                closed: false,
                                fill: egui::Color32::TRANSPARENT,
                                stroke: egui::epaint::PathStroke::new(
                                    (*thickness).max(1) as f32,
                                    color,
                                ),
                            };
                            painter.add(shape);
                            *idx += 1;
                        }
                        _ => {
                            // Unexpected op inside painter - stop painter
                            break;
                        }
                    }
                }
            }
            Op::PainterRect { .. }
            | Op::PainterCircle { .. }
            | Op::PainterLine { .. }
            | Op::PainterText { .. }
            | Op::PainterRectStroke { .. }
            | Op::PainterCircleStroke { .. }
            | Op::PainterCubicBezier { .. }
            | Op::PainterEnd => {
                // These should be consumed within PainterBegin; skip to avoid infinite loop
                *idx += 1;
            }
        }
    }
}
