#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Generate a devilspie2 rule file based on current xrandr monitor layout.

Usage:
  generate-devilspie2.sh [options]

Options:
  -m, --monitor IDX    Monitor index from `xrandr --listmonitors` (0-based). Default: 1
  --output-name NAME   Resolve geometry from a specific xrandr output name, e.g. HDMI-1
  -o, --output PATH    Output lua path. Default: ~/.config/devilspie2/blaulicht.lua
  --ext-prefix STR     External window title prefix. Default: bl_ext_
  --main-title STR     Main window title. Default: blaulicht
  -h, --help           Show this help.
EOF
}

monitor_idx=1
output_name=""
output="${HOME}/.config/devilspie2/blaulicht.lua"
ext_prefix="bl_ext_"
main_title="blaulicht"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -m|--monitor)
      monitor_idx="${2:-}"
      shift 2
      ;;
    --output-name)
      output_name="${2:-}"
      shift 2
      ;;
    -o|--output)
      output="${2:-}"
      shift 2
      ;;
    --ext-prefix)
      ext_prefix="${2:-}"
      shift 2
      ;;
    --main-title)
      main_title="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! command -v xrandr >/dev/null 2>&1; then
  echo "xrandr not found in PATH." >&2
  exit 1
fi

geom=""

# Prefer resolving by output name when provided.
if [[ -n "$output_name" ]]; then
  line="$(xrandr --query | awk -v output_name="$output_name" '$1 == output_name && $2 == "connected" {print $0}')"
  if [[ -n "$line" ]]; then
    geom="$(echo "$line" | sed -nE 's/.* ([0-9]+x[0-9]+\+[0-9]+\+[0-9]+).*/\1/p')"
  fi
fi

# Otherwise use xrandr --listmonitors (gives monitor indices).
if [[ -z "$geom" ]]; then
  if listmonitors_out="$(xrandr --listmonitors 2>/dev/null)"; then
    line="$(echo "$listmonitors_out" | awk -v idx="${monitor_idx}:" '$1 == idx {print $0}')"
    if [[ -n "$line" ]]; then
      geom="$(echo "$line" | awk '{print $3}')"
    fi
  fi
fi

# Fallback: pick Nth connected output from xrandr --query.
if [[ -z "$geom" ]]; then
  line="$(xrandr --query | awk '/ connected/ {print $0}' | sed -n "$((monitor_idx + 1))p")"
  if [[ -n "$line" ]]; then
    geom="$(echo "$line" | sed -nE 's/.* ([0-9]+x[0-9]+\+[0-9]+\+[0-9]+).*/\1/p')"
  fi
fi

if [[ -z "$geom" ]]; then
  if [[ -n "$output_name" ]]; then
    echo "Could not resolve geometry for output '${output_name}'." >&2
  else
    echo "Could not resolve geometry for monitor index ${monitor_idx}." >&2
  fi
  exit 1
fi

# Strip physical sizes: 1920/509x1080/286+1920+0 -> 1920x1080+1920+0
geom="$(echo "$geom" | sed -E 's#/[^x+]+##g')"

if [[ ! "$geom" =~ ^([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)$ ]]; then
  echo "Failed to parse geometry: ${geom}" >&2
  exit 1
fi

width="${BASH_REMATCH[1]}"
height="${BASH_REMATCH[2]}"
pos_x="${BASH_REMATCH[3]}"
pos_y="${BASH_REMATCH[4]}"

mkdir -p "$(dirname "$output")"

cat > "$output" <<EOF
-- Auto-generated by install/generate-devilspie2.sh
-- Monitor ${monitor_idx}: ${width}x${height}+${pos_x}+${pos_y}

local name = get_window_name() or ""
local ext_prefix = "${ext_prefix}"

if name:sub(1, #ext_prefix) == ext_prefix then
  set_window_geometry(${pos_x}, ${pos_y}, ${width}, ${height})
  undecorate_window()
elseif name == "${main_title}" then
  maximize()
  undecorate_window()
end
EOF

echo "Wrote ${output} using monitor ${monitor_idx} geometry ${width}x${height}+${pos_x}+${pos_y}"
