[package]
name = "blaulicht-core"
version = "0.6.7"
authors = ["MikMuellerDev"]
edition = "2021"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.76"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]


[features]
default = ["audio", "wayland", "wasmtime"] # ["wasmtime"]   # keep it on by default
wasmtime = ["dep:wasmtime"]
audio = ["dep:audioviz", "dep:cpal", "blaulicht-audio-engine/stream_in"]
audio-mock = ["blaulicht-audio-engine/noise"]
wayland = ["eframe/wayland"]
x11 = ["eframe/x11"]
dhat = ["dep:dhat"]

[dependencies]

# Audio
audioviz = { version = "0.6.0", features = ["serde"], optional = true }
audio_thread_priority = "0.34.0"
# audioviz = { path = "../../../audioviz/", features = ["serde"], optional = true }
cpal = { version = "0.15.3", optional = true }
blaulicht-audio-engine = { path = "../audio_engine/", default-features = false }


# Default
serde = { version = "1", features = ["derive"] }
spin_sleep = "1.2.1"
anyhow = "1.0.94"
toml = "0.8.19"
serde_json = "1.0.135"
crossbeam-channel = "0.5.14"
itertools = "0.14.0"
thread-priority = "1.2.0"
blaulicht-shared = { path = "../shared" }
blaulicht-assets = { path = "../assets" }
maplit = "1.0.2"
map-range = "0.1.2"
strum = { version = "0.27.2", features = ["derive"] }
noise = "0.9.0"
chrono = "0.4.42"
artnet_protocol = "0.4.4"
dhat = { version = "0.3.3", optional = true }
clap = { version = "4.5.56", default-features = false, features = ["derive"] }

# Wasm
wasmtime = { version = "31.0.0", optional = true, features = [ "all-arch" ] }
notify = "7.0.0"

# Midi
midir = "0.10.1"

# DMX
serialport = "4.7.3"
# enttecopendmx = "0.1.1"

# Egui
egui = "0.34.1"
egui_extras = { version = "0.34.1", features = ["svg"] }
egui_dock = "0.19.1"
eframe = { version = "0.34.1", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    #"persistence",   # Enable restoring app state when restarting the app.
] }
egui_plot = "0.35.0"
# egui_file = "0.26.0"
egui-phosphor = "0.12.0"
egui_code_editor = { version = "=0.2.24" }
egui_glow = "0.34.1"
egui-file-dialog = "0.13.0"
image = { version = "0.25", default-features = false, features = ["bmp"] }
bytemuck = "1.14.3"
sysinfo = "0.30.13"


tempdir = "0.3.7"
tracing = "0.1.44"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


[target.'cfg(target_os = "macos")'.dependencies]
mach = "0.3"
libc = "0.2"

[profile.dev.package.audioviz]
opt-level = 0
codegen-units = 16 # Maximize parallelism
debug = false      # Strip debug symbols for this crate to speed up linking

[profile.dev.package.moxcms]
opt-level = 0
codegen-units = 16
debug = false      # Strip debug symbols for this crate to speed up linking
