port = 1234
default_audio_device = "pipewire"

[stream]
fft_resolution = 4096
refresh_rate = 60
gravity = 100.0

[stream.processor]
sample_rate = 44100
frequency_bounds = [
    40,
    20000,
]
volume = 1.0
volume_normalisation = "Mixture"
position_normalisation = "Harmonic"
interpolation = "Cubic"

[[plugins]]
file_path = "../plugins/output.wasm"
enabled = true
enable_watcher = true
