port = 1234
dmx_out_devices = [
    "/dev/ttyUSB0",
    "/dev/dmx_out_0",
]
default_audio_device = "pipewire"
run_setup_on_reload = false
spectrogram_window_seconds = 10
spectrogram_refresh_hz = 60
last_open_showfile = "/home/mik/work/private/blaulicht/17.01_migrated.json"

[stream]
channel_count = 2
fft_resolution = 4096
refresh_rate = 60
gravity = 100.0

[stream.processor]
sampling_rate = 48000
frequency_bounds = [
    40,
    20000,
]
volume = 1.0
volume_normalisation = "Mixture"
position_normalisation = "Harmonic"
interpolation = "Cubic"

[[plugins]]
file_path = "../plugins/bundle_debug/test.wasm"
enabled = false
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/led_tubes.wasm"
enabled = true
enable_watcher = true

[plugin_state]
