port = 1234
dmx_out_devices = [
    "/dev/dmx_out_0",
    "/dev/dmx_out_0",
]
default_audio_device = "pipewire"
run_setup_on_reload = false
spectrogram_window_seconds = 10
spectrogram_refresh_hz = 60
last_open_showfile = "/home/mik/BL_DBG.json"

[stream]
fft_resolution = 4096
refresh_rate = 60
gravity = 100.0
channel_count = 2

[stream.processor]
sampling_rate = 48000
frequency_bounds = [
    40,
    20000,
]
volume = 1.0
volume_normalisation = "Mixture"
position_normalisation = "Harmonic"
interpolation = "Cubic"

[[plugins]]
file_path = "../plugins/bundle_debug/midi_all.wasm"
enabled = true
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/sample_egui_plugin.wasm"
enabled = false
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/drums.wasm"
enabled = false
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/433mhz_antenna.wasm"
enabled = false
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/visualizer.wasm"
enabled = false
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/test.wasm"
enabled = true
enable_watcher = true

[[plugins]]
file_path = "../plugins/bundle_debug/videowall.wasm"
enabled = true
enable_watcher = true

[plugin_state]
