prod-run:
	RUSTFLAGS=-Awarnings cargo r --message-format short --features=wayland --features=audio --features=wasmtime --features=wayland --features=x11

audio-mock-run:
	RUSTFLAGS=-Awarnings cargo r --message-format short --no-default-features --features=wayland --features=audio

mock-run:
	RUSTFLAGS=-Awarnings cargo r --message-format short --no-default-features --features wayland

