#[derive(Debug, Clone)]
pub enum WasmUiOp {
    Label(String),
    LabelStyled {
        text: String,
        size: i32,
        monospace: bool,
    },
    SetMaxWidth {
        width: i32,
    },
    SetMinWidth {
        width: i32,
    },
    Separator,
    Button {
        label: String,
        id: u8,
    },
    ButtonStyled {
        label: String,
        id: u8,
        enabled: bool,
    },
    ComboBox {
        label: String,
        id: u8,
        options: Vec<String>,
        selected: u8,
    },
    Checkbox {
        label: String,
        id: u8,
        checked: bool,
    },
    Switch {
        label: String,
        id: u8,
        value: bool,
    },
    Slider {
        label: String,
        id: u8,
        min: u8,
        max: u8,
        value: u8,
    },
    HFader {
        label: String,
        id: u8,
        min: u8,
        max: u8,
        value: u8,
    },
    // Layout control
    BeginVertical,
    EndVertical,
    BeginHorizontal,
    EndHorizontal,
    // Painter
    PainterBegin {
        id: u8,
        width: i32,
        height: i32,
    },
    PainterRect {
        x: i32,
        y: i32,
        w: i32,
        h: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    PainterCircle {
        x: i32,
        y: i32,
        radius: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    PainterLine {
        x1: i32,
        y1: i32,
        x2: i32,
        y2: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        thickness: i32,
    },
    PainterText {
        x: i32,
        y: i32,
        size: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        text: String,
    },
    PainterRectStroke {
        x: i32,
        y: i32,
        w: i32,
        h: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        thickness: i32,
    },
    PainterCircleStroke {
        x: i32,
        y: i32,
        radius: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        thickness: i32,
    },
    PainterCubicBezier {
        x1: i32,
        y1: i32,
        cx1: i32,
        cy1: i32,
        cx2: i32,
        cy2: i32,
        x2: i32,
        y2: i32,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        thickness: i32,
    },
    PainterEnd,
    // Text input
    TextEdit {
        label: String,
        id: u8,
        text: String,
    },
    TextEditMultiline {
        label: String,
        id: u8,
        text: String,
    },
    // Color picker
    ColorPicker {
        id: u8,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
    // Frames / Collapsing
    BeginFrame {
        id: u8,
    },
    BeginFrameStyled {
        id: u8,
        title: String,
        pad_x: i32,
        pad_y: i32,
        margin_x: i32,
        margin_y: i32,
    },
    BeginFrameStyledBorder {
        id: u8,
        title: String,
        pad_x: i32,
        pad_y: i32,
        margin_x: i32,
        margin_y: i32,
        border_r: u8,
        border_g: u8,
        border_b: u8,
        border_a: u8,
        border_thickness: i32,
    },
    EndFrame,
    BeginCollapsing {
        id: u8,
        title: String,
        default_open: bool,
    },
    EndCollapsing,
    // Tabs
    BeginTabs {
        id: u8,
    },
    BeginTab {
        tabs_id: u8,
        tab_id: u8,
        title: String,
    },
    EndTab,
    EndTabs,
}
